"use client";

interface ExplanationCardProps {
  topic: string;
  explanation: string;
}

export default function ExplanationCard({ topic, explanation }: ExplanationCardProps) {
  const paragraphs = explanation
    .split(/\n+/)
    .map((p) => p.trim())
    .filter(Boolean);

  return (
    <div
      className="
        mt-8 p-8 rounded-3xl border border-[#1a1a2e]/10
        bg-white/80 backdrop-blur-sm shadow-xl shadow-[#1a1a2e]/5
        animate-[fadeUp_0.5s_ease_forwards]
      "
      style={{ animationFillMode: "both" }}
    >
      {/* Topic label */}
      <div className="flex items-center gap-3 mb-6">
        <span
          className="
            inline-block px-3 py-1 rounded-full text-xs font-medium tracking-wide uppercase
            bg-[#e8643a]/10 text-[#e8643a] border border-[#e8643a]/20
          "
        >
          Topic
        </span>
        <h2
          className="text-2xl font-bold text-[#1a1a2e]"
          style={{ fontFamily: "var(--font-display), serif" }}
        >
          {topic}
        </h2>
      </div>

      {/* Divider */}
      <div className="h-px bg-gradient-to-r from-[#e8643a]/30 via-[#1a1a2e]/10 to-transparent mb-6" />

      {/* Explanation paragraphs */}
      <div className="space-y-4">
        {paragraphs.map((para, i) => (
          <p
            key={i}
            className="text-[#1a1a2e]/80 leading-relaxed text-[15px]"
            style={{
              animationDelay: `${i * 80}ms`,
              animationFillMode: "both",
            }}
          >
            {para}
          </p>
        ))}
      </div>

      {/* Footer hint */}
      <p className="mt-6 text-xs text-[#1a1a2e]/30 italic">
        Generated by AI · Always verify with your textbook
      </p>
    </div>
  );
}
